
import { Question } from './types';

export const quizBank: Question[] = [
  { id: "LSVN.0001", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua đầu tiên của nước Việt Nam là ai?", o: ["Kinh Dương Vương", "Hùng Vương", "An Dương Vương", "Ngô Quyền"], a: "Kinh Dương Vương" },
  { id: "LSVN.0002", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Nhà nước đầu tiên của người Việt có tên là gì?", o: ["Âu Lạc", "Vạn Xuân", "Văn Lang", "Đại Việt"], a: "Văn Lang" },
  { id: "LSVN.0003", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "An Dương Vương đặt tên nước là gì?", o: ["Âu Lạc", "Vạn Xuân", "Nam Việt", "Đại Cồ Việt"], a: "Âu Lạc" },
  { id: "LSVN.0004", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thành Cổ Loa được xây dựng dưới thời vua nào?", o: ["Hùng Vương", "An Dương Vương", "Lý Nam Đế", "Ngô Quyền"], a: "An Dương Vương" },
  { id: "LSVN.0005", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hai Bà Trưng phất cờ khởi nghĩa vào năm nào?", o: ["Năm 40", "Năm 43", "Năm 938", "Năm 542"], a: "Năm 40" },
  { id: "LSVN.0006", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người lãnh đạo cuộc khởi nghĩa Lam Sơn?", o: ["Lê Lợi", "Nguyễn Trãi", "Trần Hưng Đạo", "Quang Trung"], a: "Lê Lợi" },
  { id: "LSVN.0007", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ngô Quyền đánh tan quân Nam Hán trên sông nào?", o: ["Sông Hồng", "Sông Bạch Đằng", "Sông Cầu", "Sông Gianh"], a: "Sông Bạch Đằng" },
  { id: "LSVN.0008", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Triều đại nào dài nhất trong lịch sử Việt Nam?", o: ["Nhà Trần", "Nhà Lê", "Nhà Lý", "Nhà Nguyễn"], a: "Nhà Lê" },
  { id: "LSVN.0009", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Đinh Bộ Lĩnh dẹp loạn bao nhiêu sứ quân?", o: ["10", "11", "12", "15"], a: "12" },
  { id: "LSVN.0010", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua nào quyết định dời đô về Thăng Long?", o: ["Lý Thái Tổ", "Lý Thái Tông", "Lý Nhân Tông", "Trần Thái Tông"], a: "Lý Thái Tổ" },
  { id: "LSVN.0011", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Quốc tử giám - trường Đại học đầu tiên của Việt Nam được xây dựng năm nào?", o: ["1070", "1076", "1010", "1225"], a: "1076" },
  { id: "LSVN.0012", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là tác giả của 'Bình Ngô Đại Cáo'?", o: ["Nguyễn Trãi", "Lê Lợi", "Lê Thánh Tông", "Trần Hưng Đạo"], a: "Nguyễn Trãi" },
  { id: "LSVN.0013", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Trận thắng Điện Biên Phủ diễn ra vào năm nào?", o: ["1945", "1954", "1975", "1930"], a: "1954" },
  { id: "LSVN.0014", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua nào được mệnh danh là 'Vua Phật'?", o: ["Trần Nhân Tông", "Lý Thánh Tông", "Lê Thánh Tông", "Minh Mạng"], a: "Trần Nhân Tông" },
  { id: "LSVN.0015", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Đảng Cộng sản Việt Nam ra đời vào ngày tháng năm nào?", o: ["03/02/1930", "02/09/1945", "19/05/1890", "22/12/1944"], a: "03/02/1930" },
  { id: "LSVN.0016", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người cắm cờ trên dinh Độc Lập ngày 30/4/1975?", o: ["Bùi Quang Thận", "Phạm Tuân", "Nguyễn Văn Trỗi", "Võ Nguyên Giáp"], a: "Bùi Quang Thận" },
  { id: "LSVN.0017", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cuộc khởi nghĩa của Bà Triệu diễn ra vào thế kỷ nào?", o: ["Thế kỷ II", "Thế kỷ III", "Thế kỷ IV", "Thế kỷ V"], a: "Thế kỷ III" },
  { id: "LSVN.0018", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Triều đại nhà Trần bắt đầu từ năm nào?", o: ["1225", "1010", "1428", "1802"], a: "1225" },
  { id: "LSVN.0019", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị trạng nguyên trẻ tuổi nhất Việt Nam là ai?", o: ["Nguyễn Hiền", "Lê Văn Hưu", "Mạc Đĩnh Chi", "Lương Thế Vinh"], a: "Nguyễn Hiền" },
  { id: "LSVN.0020", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thăng Long được đổi tên thành Hà Nội vào năm nào?", o: ["1831", "1010", "1945", "1802"], a: "1831" },
  { id: "LSVN.0021", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua cuối cùng của triều đại phong kiến Việt Nam là ai?", o: ["Bảo Đại", "Khải Định", "Minh Mạng", "Duy Tân"], a: "Bảo Đại" },
  { id: "LSVN.0022", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chiến dịch Hồ Chí Minh giải phóng miền Nam kết thúc vào ngày nào?", o: ["30/04/1975", "07/05/1954", "02/09/1945", "19/12/1946"], a: "30/04/1975" },
  { id: "LSVN.0023", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hồ Chí Minh đọc bản Tuyên ngôn Độc lập tại đâu?", o: ["Quảng trường Ba Đình", "Dinh Độc Lập", "Nhà hát Lớn", "Bến Nhà Rồng"], a: "Quảng trường Ba Đình" },
  { id: "LSVN.0024", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tên cũ của Sài Gòn trước năm 1976 là gì?", o: ["Gia Định", "Chợ Lớn", "Thành phố Hồ Chí Minh", "Đà Nẵng"], a: "Gia Định" },
  { id: "LSVN.0025", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cuộc kháng chiến chống quân Nguyên Mông lần thứ 2 diễn ra vào năm nào?", o: ["1285", "1258", "1288", "1427"], a: "1285" },
  { id: "LSVN.0026", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tác giả của 'Hịch Tướng Sĩ' là ai?", o: ["Trần Hưng Đạo", "Trần Quang Khải", "Trần Nhật Duật", "Trần Quốc Toản"], a: "Trần Hưng Đạo" },
  { id: "LSVN.0027", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thủ đô của nước ta dưới thời vua Quang Trung là ở đâu?", o: ["Phú Xuân", "Thăng Long", "Hoa Lư", "Cổ Loa"], a: "Phú Xuân" },
  { id: "LSVN.0028", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Năm 1930, cuộc khởi nghĩa Yên Bái do ai lãnh đạo?", o: ["Nguyễn Thái Học", "Phan Bội Châu", "Phan Châu Trinh", "Lương Ngọc Quyến"], a: "Nguyễn Thái Học" },
  { id: "LSVN.0029", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Người thầy giáo được mệnh danh là 'Vạn thế sư biểu' của Việt Nam là ai?", o: ["Chu Văn An", "Nguyễn Bỉnh Khiêm", "Lê Quý Đôn", "Nguyễn Thiếp"], a: "Chu Văn An" },
  { id: "LSVN.0030", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Quân đội Nhân dân Việt Nam được thành lập ngày nào?", o: ["22/12/1944", "19/08/1945", "03/02/1930", "22/12/1945"], a: "22/12/1944" },
  { id: "LSVN.0031", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người anh hùng nhỏ tuổi bóp nát quả cam vì không được dự bàn việc nước?", o: ["Trần Quốc Toản", "Kim Đồng", "Võ Thị Sáu", "Lê Văn Tám"], a: "Trần Quốc Toản" },
  { id: "LSVN.0032", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Năm 1010, Lý Thái Tổ dời đô từ đâu về Thăng Long?", o: ["Hoa Lư", "Cổ Loa", "Phú Xuân", "Tây Đô"], a: "Hoa Lư" },
  { id: "LSVN.0033", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Bộ luật thành văn đầu tiên của nước ta là gì?", o: ["Hình thư", "Quốc triều hình luật", "Luật Gia Long", "Luật Hồng Đức"], a: "Hình thư" },
  { id: "LSVN.0034", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người phụ nữ duy nhất làm vua trong lịch sử Việt Nam?", o: ["Lý Chiêu Hoàng", "Nguyên Phi Ỷ Lan", "Thái hậu Dương Vân Nga", "Bà Triệu"], a: "Lý Chiêu Hoàng" },
  { id: "LSVN.0035", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Nhà Hồ tồn tại trong khoảng thời gian nào?", o: ["1400 - 1407", "1225 - 1400", "1428 - 1527", "1802 - 1820"], a: "1400 - 1407" },
  { id: "LSVN.0036", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vương triều nào đã đánh thắng quân Thanh năm 1789?", o: ["Nhà Tây Sơn", "Nhà Lê", "Nhà Nguyễn", "Nhà Mạc"], a: "Nhà Tây Sơn" },
  { id: "LSVN.0037", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thành phố cảng nào là nơi thực dân Pháp nổ súng xâm lược Việt Nam đầu tiên năm 1858?", o: ["Đà Nẵng", "Hải Phòng", "Sài Gòn", "Huế"], a: "Đà Nẵng" },
  { id: "LSVN.0038", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người lãnh đạo cuộc khởi nghĩa Hương Khê?", o: ["Phan Đình Phùng", "Hoàng Hoa Thám", "Nguyễn Thiện Thuật", "Đinh Công Tráng"], a: "Phan Đình Phùng" },
  { id: "LSVN.0039", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cố đô Huế được UNESCO công nhận là Di sản Văn hóa Thế giới vào năm nào?", o: ["1993", "1999", "2003", "1990"], a: "1993" },
  { id: "LSVN.0040", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là tác giả của 'Nam quốc sơn hà'?", o: ["Lý Thường Kiệt", "Trần Hưng Đạo", "Nguyễn Trãi", "Không rõ tác giả"], a: "Lý Thường Kiệt" },
  { id: "LSVN.0041", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Lý Nam Đế đặt tên nước ta là gì?", o: ["Vạn Xuân", "Đại Việt", "Âu Lạc", "Đại Cồ Việt"], a: "Vạn Xuân" },
  { id: "LSVN.0042", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người dâng 'Thất trảm sớ' đòi chém 7 nịnh thần?", o: ["Chu Văn An", "Nguyễn Trãi", "Tô Hiến Thành", "Trần Thủ Độ"], a: "Chu Văn An" },
  { id: "LSVN.0043", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Kinh đô của nhà Nguyễn nằm ở đâu?", o: ["Huế", "Hà Nội", "Thanh Hóa", "Gia Định"], a: "Huế" },
  { id: "LSVN.0044", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người thực hiện cải cách tiền giấy đầu tiên ở Việt Nam?", o: ["Hồ Quý Ly", "Lê Thánh Tông", "Minh Mạng", "Trần Anh Tông"], a: "Hồ Quý Ly" },
  { id: "LSVN.0045", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thái sư Trần Thủ Độ có câu nói nổi tiếng nào?", o: ["Đầu thần chưa rơi xuống đất...", "Sát Thát", "Bình Ngô", "Phá cường địch"], a: "Đầu thần chưa rơi xuống đất..." },
  { id: "LSVN.0046", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ngày giải phóng Thủ đô Hà Nội là ngày nào?", o: ["10/10/1954", "02/09/1945", "19/05/1954", "30/04/1975"], a: "10/10/1954" },
  { id: "LSVN.0047", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Anh hùng Núp tham gia kháng chiến ở vùng nào?", o: ["Tây Nguyên", "Bắc Bộ", "Nam Bộ", "Miền Trung"], a: "Tây Nguyên" },
  { id: "LSVN.0048", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chiến dịch Điện Biên Phủ trên không diễn ra vào năm nào?", o: ["1972", "1968", "1975", "1954"], a: "1972" },
  { id: "LSVN.0049", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Người thiếu niên anh hùng lấy thân mình lấp lỗ châu mai?", o: ["Phan Đình Giót", "Tô Vĩnh Diện", "Bế Văn Đàn", "Lê Văn Tám"], a: "Phan Đình Giót" },
  { id: "LSVN.0050", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Việt Nam gia nhập ASEAN vào năm nào?", o: ["1995", "1997", "1991", "2000"], a: "1995" },
  { id: "LSVN.0051", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tên thật của Mạc Đĩnh Chi là gì?", o: ["Mạc Đĩnh Chi", "Mạc Đăng Dung", "Mạc Tử Sanh", "Mạc Cửu"], a: "Mạc Đĩnh Chi" },
  { id: "LSVN.0052", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hải Thượng Lãn Ông là tên hiệu của ai?", o: ["Lê Hữu Trác", "Tuệ Tĩnh", "Phan Huy Chú", "Nguyễn Du"], a: "Lê Hữu Trác" },
  { id: "LSVN.0053", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai lãnh đạo phong trào Cần Vương giai đoạn đầu?", o: ["Hàm Nghi và Tôn Thất Thuyết", "Duy Tân", "Thành Thái", "Phan Đình Phùng"], a: "Hàm Nghi và Tôn Thất Thuyết" },
  { id: "LSVN.0054", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cầu Long Biên do nước nào xây dựng?", o: ["Pháp", "Mỹ", "Trung Quốc", "Nga"], a: "Pháp" },
  { id: "LSVN.0055", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Trận Rạch Gầm - Xoài Mút tiêu diệt quân nào?", o: ["Quân Xiêm", "Quân Thanh", "Quân Pháp", "Quân Anh"], a: "Quân Xiêm" },
  { id: "LSVN.0056", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Nguyễn Tất Thành ra đi tìm đường cứu nước từ đâu?", o: ["Bến Nhà Rồng", "Hải Phòng", "Đà Nẵng", "Vinh"], a: "Bến Nhà Rồng" },
  { id: "LSVN.0057", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tổng khởi nghĩa tháng Tám diễn ra vào năm nào?", o: ["1945", "1944", "1946", "1930"], a: "1945" },
  { id: "LSVN.0058", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người soạn thảo Luận cương Chính trị tháng 10/1930?", o: ["Trần Phú", "Hồ Chí Minh", "Lê Hồng Phong", "Hà Huy Tập"], a: "Trần Phú" },
  { id: "LSVN.0059", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chiến thắng 'Hà Nội - Điện Biên Phủ trên không' diễn ra trong bao nhiêu ngày đêm?", o: ["12", "10", "15", "20"], a: "12" },
  { id: "LSVN.0060", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Bản Tuyên ngôn Độc lập năm 1945 khẳng định điều gì?", o: ["Quyền tự do và độc lập", "Quyền được sống", "Quyền mưu cầu hạnh phúc", "Tất cả các phương án trên"], a: "Tất cả các phương án trên" },
  { id: "LSVN.0061", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vạn Thắng Vương là danh hiệu của ai?", o: ["Đinh Bộ Lĩnh", "Lê Hoàn", "Ngô Quyền", "Quang Trung"], a: "Đinh Bộ Lĩnh" },
  { id: "LSVN.0062", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Lý Thường Kiệt lãnh đạo cuộc kháng chiến chống quân xâm lược nào?", o: ["Quân Tống", "Quân Nguyên", "Quân Minh", "Quân Thanh"], a: "Quân Tống" },
  { id: "LSVN.0063", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cuộc kháng chiến chống quân Nguyên Mông lần thứ nhất năm nào?", o: ["1258", "1285", "1288", "1225"], a: "1258" },
  { id: "LSVN.0064", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Trần Hưng Đạo tên thật là gì?", o: ["Trần Quốc Tuấn", "Trần Quốc Toản", "Trần Quang Khải", "Trần Nhật Duật"], a: "Trần Quốc Tuấn" },
  { id: "LSVN.0065", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Sách 'Đại Việt sử ký' do ai biên soạn?", o: ["Lê Văn Hưu", "Ngô Sĩ Liên", "Phan Huy Chú", "Lương Thế Vinh"], a: "Lê Văn Hưu" },
  { id: "LSVN.0066", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua nào sáng lập ra nhà Hậu Lê?", o: ["Lê Lợi", "Lê Thái Tông", "Lê Thánh Tông", "Lê Hiến Tông"], a: "Lê Lợi" },
  { id: "LSVN.0067", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Địa danh nào gắn liền với chiến thắng quân Minh của Lê Lợi?", o: ["Chi Lăng - Xương Giang", "Bạch Đằng", "Ngọc Hồi - Đống Đa", "Rạch Gầm"], a: "Chi Lăng - Xương Giang" },
  { id: "LSVN.0068", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Lê Thánh Tông nổi tiếng với tập bản đồ nào?", o: ["Hồng Đức", "Đại Nam", "Toàn thư", "Dư địa chí"], a: "Hồng Đức" },
  { id: "LSVN.0069", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chúa Trịnh và Chúa Nguyễn lấy sông nào làm ranh giới?", o: ["Sông Gianh", "Sông Bến Hải", "Sông Hồng", "Sông Hương"], a: "Sông Gianh" },
  { id: "LSVN.0070", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người lãnh đạo cuộc khởi nghĩa Tây Sơn?", o: ["Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ", "Nguyễn Huệ", "Nguyễn Ánh", "Nguyễn Du"], a: "Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ" },
  { id: "LSVN.0071", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vua Quang Trung mất năm nào?", o: ["1792", "1789", "1802", "1771"], a: "1792" },
  { id: "LSVN.0072", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Triều Nguyễn bắt đầu từ năm nào?", o: ["1802", "1858", "1945", "1789"], a: "1802" },
  { id: "LSVN.0073", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Phan Bội Châu khởi xướng phong trào nào?", o: ["Đông Du", "Duy Tân", "Cần Vương", "Xô Viết Nghệ Tĩnh"], a: "Đông Du" },
  { id: "LSVN.0074", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Việt Nam Quang phục hội do ai thành lập?", o: ["Phan Bội Châu", "Phan Châu Trinh", "Hồ Chí Minh", "Lê Hồng Phong"], a: "Phan Bội Châu" },
  { id: "LSVN.0075", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hội Việt Nam Cách mạng Thanh niên thành lập ở đâu?", o: ["Quảng Châu (Trung Quốc)", "Hà Nội", "Sài Gòn", "Paris"], a: "Quảng Châu (Trung Quốc)" },
  { id: "LSVN.0076", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Phong trào Xô Viết Nghệ Tĩnh diễn ra năm nào?", o: ["1930-1931", "1936-1939", "1940", "1945"], a: "1930-1931" },
  { id: "LSVN.0077", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Mặt trận Việt Minh thành lập năm nào?", o: ["1941", "1930", "1945", "1951"], a: "1941" },
  { id: "LSVN.0078", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chỉ thị 'Nhật - Pháp bắn nhau và hành động của chúng ta' ra đời năm nào?", o: ["1945", "1944", "1940", "1946"], a: "1945" },
  { id: "LSVN.0079", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hiệp định Geneve về Đông Dương được ký kết năm nào?", o: ["1954", "1945", "1973", "1946"], a: "1954" },
  { id: "LSVN.0080", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Hiệp định Paris về Việt Nam được ký kết năm nào?", o: ["1973", "1954", "1975", "1968"], a: "1973" },
  { id: "LSVN.0081", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Đường mòn Hồ Chí Minh trên biển gắn liền với loại tàu nào?", o: ["Tàu không số", "Tàu ngầm", "Tàu chiến", "Tàu vận tải"], a: "Tàu không số" },
  { id: "LSVN.0082", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người lãnh đạo nữ duy nhất của quân đội ta trong thời kỳ chống Mỹ?", o: ["Nguyễn Thị Định", "Võ Thị Sáu", "Bùi Thị Xuân", "Nguyễn Thị Chiên"], a: "Nguyễn Thị Định" },
  { id: "LSVN.0083", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Trận 'Điện Biên Phủ trên không' diễn ra chủ yếu ở đâu?", o: ["Hà Nội, Hải Phòng", "Sài Gòn", "Đà Nẵng", "Quảng Trị"], a: "Hà Nội, Hải Phòng" },
  { id: "LSVN.0084", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Việt Nam thực hiện công cuộc Đổi mới từ năm nào?", o: ["1986", "1975", "1990", "1995"], a: "1986" },
  { id: "LSVN.0085", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Đại hội Đảng lần thứ mấy khởi xướng công cuộc Đổi mới?", o: ["VI", "IV", "V", "VII"], a: "VI" },
  { id: "LSVN.0086", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị Đại tướng đầu tiên của Việt Nam là ai?", o: ["Võ Nguyên Giáp", "Văn Tiến Dũng", "Nguyễn Chí Thanh", "Chu Huy Mân"], a: "Võ Nguyên Giáp" },
  { id: "LSVN.0087", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Quần đảo Trường Sa và Hoàng Sa thuộc chủ quyền của quốc gia nào?", o: ["Việt Nam", "Trung Quốc", "Philippines", "Malaysia"], a: "Việt Nam" },
  { id: "LSVN.0088", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ngày Thương binh Liệt sĩ là ngày nào?", o: ["27/07", "22/12", "19/08", "30/04"], a: "27/07" },
  { id: "LSVN.0089", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Người anh hùng lấy thân mình chèn pháo?", o: ["Tô Vĩnh Diện", "Phan Đình Giót", "Bế Văn Đàn", "Trần Can"], a: "Tô Vĩnh Diện" },
  { id: "LSVN.0090", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tên thật của chủ tịch Hồ Chí Minh khi mới sinh là gì?", o: ["Nguyễn Sinh Cung", "Nguyễn Tất Thành", "Văn Ba", "Nguyễn Ái Quốc"], a: "Nguyễn Sinh Cung" },
  { id: "LSVN.0091", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Chùa Một Cột được xây dựng dưới thời vua nào?", o: ["Lý Thái Tông", "Lý Thái Tổ", "Trần Thái Tông", "Lê Thánh Tông"], a: "Lý Thái Tông" },
  { id: "LSVN.0092", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Lễ hội Đền Hùng được tổ chức vào ngày nào âm lịch?", o: ["10/03", "15/01", "05/05", "15/08"], a: "10/03" },
  { id: "LSVN.0093", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tác giả của tác phẩm 'Truyện Kiều' là ai?", o: ["Nguyễn Du", "Đoàn Thị Điểm", "Hồ Xuân Hương", "Nguyễn Trãi"], a: "Nguyễn Du" },
  { id: "LSVN.0094", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Cái tên 'Việt Nam' chính thức được sử dụng làm quốc hiệu từ thời vua nào?", o: ["Gia Long", "Minh Mạng", "Quang Trung", "Hồ Chí Minh"], a: "Gia Long" },
  { id: "LSVN.0095", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Kỳ đài (Cột cờ) lớn nhất Việt Nam thời phong kiến nằm ở đâu?", o: ["Huế", "Hà Nội", "Nam Định", "Thanh Hóa"], a: "Huế" },
  { id: "LSVN.0096", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người sáng lập ra nhà Trần?", o: ["Trần Cảnh (vua) và Trần Thủ Độ", "Trần Hưng Đạo", "Trần Thừa", "Trần Quang Khải"], a: "Trần Cảnh (vua) và Trần Thủ Độ" },
  { id: "LSVN.0097", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Nữ sĩ được mệnh danh là 'Bà chúa thơ Nôm' là ai?", o: ["Hồ Xuân Hương", "Đoàn Thị Điểm", "Bà Huyện Thanh Quan", "Ngọc Hân Công Chúa"], a: "Hồ Xuân Hương" },
  { id: "LSVN.0098", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua nào thực hiện cuộc cải cách hành chính chia nước làm 30 tỉnh năm 1831?", o: ["Minh Mạng", "Gia Long", "Thiệu Trị", "Tự Đức"], a: "Minh Mạng" },
  { id: "LSVN.0099", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Tên gọi của nước ta dưới thời nhà Hồ là gì?", o: ["Đại Ngu", "Đại Việt", "Đại Cồ Việt", "Âu Lạc"], a: "Đại Ngu" },
  { id: "LSVN.0100", classTag: "LSVN", part: "QuiZ vui vẻ!", type: "mcq", question: "Thành phố nào được mệnh danh là 'Thành phố vì hòa bình'?", o: ["Hà Nội", "Đà Nẵng", "Huế", "Thành phố Hồ Chí Minh"], a: "Hà Nội" },
  { id: "LSTG.0001", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Kim tự tháp là công trình kiến trúc của quốc gia cổ đại nào?", o: ["Ai Cập", "Lưỡng Hà", "Ấn Độ", "Hy Lạp"], a: "Ai Cập" },
  { id: "LSTG.0002", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Người phát minh ra máy hơi nước đầu tiên là ai?", o: ["James Watt", "Newton", "Edison", "Faraday"], a: "James Watt" },
  { id: "LSTG.0003", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thế chiến thứ nhất diễn ra trong khoảng thời gian nào?", o: ["1914 - 1918", "1939 - 1945", "1911 - 1913", "1945 - 1950"], a: "1914 - 1918" },
  { id: "LSTG.0004", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Cuộc Cách mạng Pháp nổ ra vào năm nào?", o: ["1789", "1776", "1848", "1917"], a: "1789" },
  { id: "LSTG.0005", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người tìm ra châu Mỹ năm 1492?", o: ["Christopher Columbus", "Vasco da Gama", "Magellan", "Amerigo Vespucci"], a: "Christopher Columbus" },
  { id: "LSTG.0006", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Liên minh Châu Âu (EU) có trụ sở chính tại đâu?", o: ["Brussels (Bỉ)", "Paris (Pháp)", "Berlin (Đức)", "London (Anh)"], a: "Brussels (Bỉ)" },
  { id: "LSTG.0007", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thế chiến thứ hai kết thúc vào năm nào?", o: ["1945", "1944", "1946", "1950"], a: "1945" },
  { id: "LSTG.0008", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Pharaoh là tên gọi các vị vua của quốc gia nào?", o: ["Ai Cập", "Ấn Độ", "Trung Quốc", "Hy Lạp"], a: "Ai Cập" },
  { id: "LSTG.0009", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người đầu tiên bay vào vũ trụ?", o: ["Yuri Gagarin", "Neil Armstrong", "Phạm Tuân", "Albert Einstein"], a: "Yuri Gagarin" },
  { id: "LSTG.0010", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Liên Hợp Quốc được thành lập vào năm nào?", o: ["1945", "1919", "1950", "1941"], a: "1945" },
  { id: "LSTG.0011", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Vạn Lý Trường Thành là công trình của quốc gia nào?", o: ["Trung Quốc", "Ấn Độ", "Nhật Bản", "Mông Cổ"], a: "Trung Quốc" },
  { id: "LSTG.0012", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Đấu trường La Mã (Colosseum) nằm ở quốc gia nào?", o: ["Ý", "Hy Lạp", "Pháp", "Đức"], a: "Ý" },
  { id: "LSTG.0013", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Hệ thống chữ số chúng ta đang dùng (0-9) có nguồn gốc ban đầu từ đâu?", o: ["Ấn Độ", "Ả Rập", "La Mã", "Hy Lạp"], a: "Ấn Độ" },
  { id: "LSTG.0014", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Cách mạng tháng Mười Nga diễn ra năm nào?", o: ["1917", "1905", "1921", "1945"], a: "1917" },
  { id: "LSTG.0015", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là tác giả của thuyết Tương đối?", o: ["Albert Einstein", "Isaac Newton", "Stephen Hawking", "Marie Curie"], a: "Albert Einstein" },
  { id: "LSTG.0016", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thời kỳ Phục hưng bắt đầu từ quốc gia nào?", o: ["Ý", "Pháp", "Anh", "Đức"], a: "Ý" },
  { id: "LSTG.0017", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Bức tường Berlin sụp đổ vào năm nào?", o: ["1989", "1991", "1945", "1975"], a: "1989" },
  { id: "LSTG.0018", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Kinh đô của Đế chế La Mã thời cực thịnh là gì?", o: ["Roma", "Constantinople", "Athens", "Alexandria"], a: "Roma" },
  { id: "LSTG.0019", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thành phố nào bị Mỹ ném bom nguyên tử đầu tiên?", o: ["Hiroshima", "Nagasaki", "Tokyo", "Osaka"], a: "Hiroshima" },
  { id: "LSTG.0020", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Napoleon Bonaparte là hoàng đế của nước nào?", o: ["Pháp", "Anh", "Đức", "Ý"], a: "Pháp" },
  { id: "LSTG.0021", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Sự kiện nào đánh dấu sự bắt đầu của Thế chiến 2 tại Châu Âu?", o: ["Đức tấn công Ba Lan", "Nhật tấn công Trân Châu Cảng", "Ý xâm lược Ethiopia", "Anh tuyên chiến với Đức"], a: "Đức tấn công Ba Lan" },
  { id: "LSTG.0022", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người lãnh đạo cuộc giành độc lập của Ấn Độ?", o: ["Mahatma Gandhi", "Jawaharlal Nehru", "Hoàng đế Ashoka", "Akbar Đại đế"], a: "Mahatma Gandhi" },
  { id: "LSTG.0023", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Kênh đào Suez nối liền hai biển nào?", o: ["Địa Trung Hải và Biển Đỏ", "Đại Tây Dương và Thái Bình Dương", "Biển Đen và Địa Trung Hải", "Biển Đông và Ấn Độ Dương"], a: "Địa Trung Hải và Biển Đỏ" },
  { id: "LSTG.0024", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Vị vua nào của Macedonia đã chinh phục đế chế Ba Tư?", o: ["Alexander Đại đế", "Philip II", "Julius Caesar", "Pericles"], a: "Alexander Đại đế" },
  { id: "LSTG.0025", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Đế quốc nào đã tồn tại lâu nhất trong lịch sử nhân loại?", o: ["Đế chế La Mã", "Đế quốc Mông Cổ", "Đế quốc Ottoman", "Đế chế Anh"], a: "Đế chế La Mã" },
  { id: "LSTG.0026", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "ASEAN được thành lập vào ngày tháng năm nào?", o: ["08/08/1967", "01/01/1995", "11/11/1975", "02/09/1945"], a: "08/08/1967" },
  { id: "LSTG.0027", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là tổng thống đầu tiên của Hợp chủng quốc Hoa Kỳ?", o: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Franklin Roosevelt"], a: "George Washington" },
  { id: "LSTG.0028", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Loại vũ khí nào được sử dụng lần đầu trong Thế chiến 1?", o: ["Xe tăng", "Súng hỏa mai", "Máy bay ném bom nguyên tử", "Tên lửa đạn đạo"], a: "Xe tăng" },
  { id: "LSTG.0029", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Văn minh Lưỡng Hà nằm giữa hai con sông nào?", o: ["Tigris và Euphrates", "Sông Ấn và sông Hằng", "Sông Nile", "Sông Hoàng Hà"], a: "Tigris và Euphrates" },
  { id: "LSTG.0030", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Năm 1917, nước nào rút khỏi Thế chiến thứ nhất?", o: ["Nga", "Mỹ", "Pháp", "Đức"], a: "Nga" },
  { id: "LSTG.0031", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Chế độ phân biệt chủng tộc Apartheid tồn tại ở quốc gia nào?", o: ["Nam Phi", "Mỹ", "Úc", "Zimbabwe"], a: "Nam Phi" },
  { id: "LSTG.0032", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Tên gọi của cuộc thám hiểm vòng quanh thế giới đầu tiên là của ai?", o: ["Ferdinand Magellan", "James Cook", "Marco Polo", "Columbus"], a: "Ferdinand Magellan" },
  { id: "LSTG.0033", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người phát minh ra điện thoại?", o: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"], a: "Alexander Graham Bell" },
  { id: "LSTG.0034", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thế vận hội Olympic hiện đại đầu tiên được tổ chức tại đâu?", o: ["Athens (Hy Lạp)", "Paris (Pháp)", "London (Anh)", "Rome (Ý)"], a: "Athens (Hy Lạp)" },
  { id: "LSTG.0035", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Leonardo da Vinci là danh họa nổi tiếng thời nào?", o: ["Phục hưng", "Cổ đại", "Trung cổ", "Hiện đại"], a: "Phục hưng" },
  { id: "LSTG.0036", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Đất nước nào là quê hương của cuộc Cách mạng công nghiệp?", o: ["Anh", "Pháp", "Mỹ", "Đức"], a: "Anh" },
  { id: "LSTG.0037", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Nhật Bản thực hiện cuộc Duy Tân Minh Trị vào năm nào?", o: ["1868", "1905", "1888", "1850"], a: "1868" },
  { id: "LSTG.0038", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Đế quốc Mông Cổ được thành lập bởi ai?", o: ["Thành Cát Tư Hãn", "Hốt Tất Liệt", "Bạt Đô", "Tamerlane"], a: "Thành Cát Tư Hãn" },
  { id: "LSTG.0039", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Tổ chức thương mại thế giới có tên viết tắt là gì?", o: ["WTO", "WHO", "IMF", "WB"], a: "WTO" },
  { id: "LSTG.0040", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Chiến tranh lạnh là cuộc đối đầu giữa hai cực nào?", o: ["Mỹ và Liên Xô", "Anh và Pháp", "Đức và Nhật", "Trung Quốc và Ấn Độ"], a: "Mỹ và Liên Xô" },
  { id: "LSTG.0041", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Titanic bị chìm vào năm nào?", o: ["1912", "1900", "1915", "1920"], a: "1912" },
  { id: "LSTG.0042", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Nữ hoàng nào trị vì lâu nhất lịch sử Vương quốc Anh?", o: ["Elizabeth II", "Victoria", "Elizabeth I", "Anne"], a: "Elizabeth II" },
  { id: "LSTG.0043", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Ai là người phát minh ra bóng đèn sợi đốt?", o: ["Thomas Edison", "Benjamin Franklin", "Nikola Tesla", "Watt"], a: "Thomas Edison" },
  { id: "LSTG.0044", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Khối quân sự NATO được thành lập năm nào?", o: ["1949", "1955", "1945", "1960"], a: "1949" },
  { id: "LSTG.0045", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Hiến pháp Mỹ được thông qua vào năm nào?", o: ["1787", "1776", "1789", "1800"], a: "1787" },
  { id: "LSTG.0046", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Thành phố nào từng được gọi là Constantinople?", o: ["Istanbul", "Ankara", "Athens", "Rome"], a: "Istanbul" },
  { id: "LSTG.0047", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Năm 1969, ai là người đầu tiên đặt chân lên Mặt Trăng?", o: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], a: "Neil Armstrong" },
  { id: "LSTG.0048", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Kênh đào Panama nối hai đại dương nào?", o: ["Đại Tây Dương và Thái Bình Dương", "Ấn Độ Dương và Thái Bình Dương", "Bắc Băng Dương và Thái Bình Dương", "Địa Trung Hải và Đại Tây Dương"], a: "Đại Tây Dương và Thái Bình Dương" },
  { id: "LSTG.0049", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Đất nước nào có diện tích lớn nhất thế giới hiện nay?", o: ["Nga", "Canada", "Mỹ", "Trung Quốc"], a: "Nga" },
  { id: "LSTG.0050", classTag: "LSTG", part: "QuiZ vui vẻ!", type: "mcq", question: "Cách mạng Tân Hợi ở Trung Quốc nổ ra năm nào?", o: ["1911", "1912", "1905", "1949"], a: "1911" }
];

/**
 * Fix: Changed excludeIds type from number[] to (string | number)[] to match Question.id type 
 * and avoid type mismatch during includes() check at line 158.
 */
export const getRandomQuizQuestion = (excludeIds: (string | number)[] = []) => {
  const available = quizBank.filter(q => !excludeIds.includes(q.id));
  const pool = available.length > 0 ? available : quizBank;
  return pool[Math.floor(Math.random() * pool.length)];
};
